const mongoose = require("mongoose");
require("dotenv").config();

// 1. Database Connection Logic
const MONGO_URI =
  process.env.MONGO_URI ||
  "mongodb+srv://haxplore_db:gYIu0UmJKdsmZY08@cluster0.1t4vnav.mongodb.net/";

mongoose
  .connect(MONGO_URI)
  .then(() => console.log("Connected to MongoDB for seeding..."))
  .catch((err) => console.error("Could not connect to MongoDB:", err));

// 2. Define the Schema (Must match your backend model)
const binSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  lat: { type: Number, required: true },
  lng: { type: Number, required: true },
  address: { type: String, required: true },
  acceptedItems: [{ type: String }],
  fillLevel: { type: Number, default: 0 },
  status: {
    type: String,
    enum: ["operational", "full", "maintenance"],
    default: "operational",
  },
});

const userSchema = new mongoose.Schema({
  name: String,
  email: String,
  phone: String,
  password: String,
  userType: String,
  points: Number,
  totalRecycled: Number,
  badges: [String],
  co2Saved: Number,
});

// ✅ Detection Schema (for Recent Detects feature)
const detectionSchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },

    type: String,
    name: String,
    confidence: Number,
    weight: Number,
    value: Number,
    points: Number,
    co2Saved: Number,
    condition: String,
    image: String,

    confirmed: { type: Boolean, default: true },
  },
  { timestamps: true }
);

const Bin = mongoose.model("Bin", binSchema);
const User = mongoose.model("User", userSchema);
const Detection = mongoose.model("Detection", detectionSchema);

// 3. The Data
const BINS = [
  /* MAHARASHTRA (MH) */
  {
    id: "mh-1",
    name: "Mumbai E-Tech Hub",
    lat: 19.076,
    lng: 72.8777,
    address: "Andheri East, Mumbai, MH",
    acceptedItems: ["phone", "battery", "charger"],
    fillLevel: 35,
    status: "operational",
  },
  {
    id: "mh-2",
    name: "BKC Green Bin",
    lat: 19.06,
    lng: 72.8697,
    address: "BKC, Mumbai, MH",
    acceptedItems: ["laptop", "hard-drive"],
    fillLevel: 55,
    status: "operational",
  },
  {
    id: "mh-3",
    name: "Navi Mumbai Recycle Point",
    lat: 19.033,
    lng: 73.0297,
    address: "Vashi, Navi Mumbai, MH",
    acceptedItems: ["phone", "tablet"],
    fillLevel: 80,
    status: "full",
  },
  {
    id: "mh-4",
    name: "Pune IT Park Bin",
    lat: 18.5204,
    lng: 73.8567,
    address: "Hinjewadi, Pune, MH",
    acceptedItems: ["battery", "cable", "charger"],
    fillLevel: 20,
    status: "operational",
  },
  {
    id: "mh-5",
    name: "Nagpur Eco Drop",
    lat: 21.1458,
    lng: 79.0882,
    address: "Sitabuldi, Nagpur, MH",
    acceptedItems: ["phone", "watch"],
    fillLevel: 40,
    status: "operational",
  },
  {
    id: "mh-6",
    name: "Nashik Digital Bin",
    lat: 19.9975,
    lng: 73.7898,
    address: "College Road, Nashik, MH",
    acceptedItems: ["laptop", "charger"],
    fillLevel: 60,
    status: "operational",
  },
  {
    id: "mh-7",
    name: "Aurangabad E-Waste Hub",
    lat: 19.8762,
    lng: 75.3433,
    address: "CIDCO, Aurangabad, MH",
    acceptedItems: ["tablet", "battery"],
    fillLevel: 25,
    status: "operational",
  },
  {
    id: "mh-8",
    name: "Thane Smart Bin",
    lat: 19.2183,
    lng: 72.9781,
    address: "Ghodbunder Rd, Thane, MH",
    acceptedItems: ["phone", "headphones"],
    fillLevel: 70,
    status: "operational",
  },
  {
    id: "mh-9",
    name: "Kolhapur E-Recycle",
    lat: 16.705,
    lng: 74.2433,
    address: "Shivaji Nagar, Kolhapur, MH",
    acceptedItems: ["cable", "charger"],
    fillLevel: 15,
    status: "operational",
  },
  {
    id: "mh-10",
    name: "Solapur Green Tech Bin",
    lat: 17.6599,
    lng: 75.9064,
    address: "Station Rd, Solapur, MH",
    acceptedItems: ["battery", "watch"],
    fillLevel: 90,
    status: "full",
  },

  /* KARNATAKA (KA) */
  {
    id: "ka-1",
    name: "Bangalore Central Bin",
    lat: 12.9716,
    lng: 77.5946,
    address: "MG Road, Bengaluru, KA",
    acceptedItems: ["phone", "laptop"],
    fillLevel: 30,
    status: "operational",
  },
  {
    id: "ka-2",
    name: "Electronic City E-Hub",
    lat: 12.8399,
    lng: 77.677,
    address: "Electronic City, KA",
    acceptedItems: ["hard-drive", "cable"],
    fillLevel: 45,
    status: "operational",
  },
  {
    id: "ka-3",
    name: "Whitefield Smart Bin",
    lat: 12.9698,
    lng: 77.75,
    address: "Whitefield, Bengaluru, KA",
    acceptedItems: ["tablet", "charger"],
    fillLevel: 60,
    status: "operational",
  },
  {
    id: "ka-4",
    name: "Mysore Digital Drop",
    lat: 12.2958,
    lng: 76.6394,
    address: "VV Mohalla, Mysuru, KA",
    acceptedItems: ["phone", "battery"],
    fillLevel: 20,
    status: "operational",
  },
  {
    id: "ka-5",
    name: "Hubli Eco Bin",
    lat: 15.3647,
    lng: 75.124,
    address: "Keshwapur, Hubli, KA",
    acceptedItems: ["laptop", "watch"],
    fillLevel: 50,
    status: "operational",
  },
  {
    id: "ka-6",
    name: "Mangalore E-Waste Point",
    lat: 12.9141,
    lng: 74.856,
    address: "Hampankatta, Mangalore, KA",
    acceptedItems: ["phone", "headphones"],
    fillLevel: 65,
    status: "operational",
  },
  {
    id: "ka-7",
    name: "Belgaum Green Tech",
    lat: 15.8497,
    lng: 74.4977,
    address: "Tilakwadi, Belgaum, KA",
    acceptedItems: ["battery", "charger"],
    fillLevel: 10,
    status: "operational",
  },
  {
    id: "ka-8",
    name: "Davangere E-Bin",
    lat: 14.4644,
    lng: 75.9218,
    address: "PJ Extension, Davangere, KA",
    acceptedItems: ["tablet", "cable"],
    fillLevel: 75,
    status: "operational",
  },
  {
    id: "ka-9",
    name: "Udupi Smart Recycle",
    lat: 13.3409,
    lng: 74.7421,
    address: "Manipal Rd, Udupi, KA",
    acceptedItems: ["phone", "watch"],
    fillLevel: 40,
    status: "operational",
  },
  {
    id: "ka-10",
    name: "Tumkur E-Drop",
    lat: 13.3392,
    lng: 77.113,
    address: "BH Road, Tumkur, KA",
    acceptedItems: ["laptop", "battery"],
    fillLevel: 85,
    status: "full",
  },

  /* DELHI (DL) */
  {
    id: "dl-1",
    name: "Connaught Place Green Bin",
    lat: 28.6139,
    lng: 77.209,
    address: "CP, New Delhi, DL",
    acceptedItems: ["phone", "charger"],
    fillLevel: 25,
    status: "operational",
  },
  {
    id: "dl-2",
    name: "Dwarka E-Waste Hub",
    lat: 28.5921,
    lng: 76.046,
    address: "Sector 10, Dwarka, DL",
    acceptedItems: ["laptop", "battery"],
    fillLevel: 55,
    status: "operational",
  },
  {
    id: "dl-3",
    name: "Rohini Smart Bin",
    lat: 29.749,
    lng: 75.0565,
    address: "Sector 3, Rohini, DL",
    acceptedItems: ["tablet", "cable"],
    fillLevel: 40,
    status: "operational",
  },
  {
    id: "dl-4",
    name: "Saket Digital Drop",
    lat: 25.5244,
    lng: 73.2066,
    address: "Saket, New Delhi, DL",
    acceptedItems: ["phone", "watch"],
    fillLevel: 15,
    status: "operational",
  },
  {
    id: "dl-5",
    name: "Karol Bagh E-Bin",
    lat: 28.6512,
    lng: 78.19,
    address: "Karol Bagh, DL",
    acceptedItems: ["battery", "headphones"],
    fillLevel: 70,
    status: "operational",
  },
  {
    id: "dl-6",
    name: "Lajpat Nagar Eco Point",
    lat: 24.5672,
    lng: 74.2436,
    address: "Lajpat Nagar, DL",
    acceptedItems: ["charger", "cable"],
    fillLevel: 60,
    status: "operational",
  },
  {
    id: "dl-7",
    name: "Pitampura Green Tech",
    lat: 28.7033,
    lng: 74.1322,
    address: "Pitampura, DL",
    acceptedItems: ["phone", "tablet"],
    fillLevel: 35,
    status: "operational",
  },
  {
    id: "dl-8",
    name: "Janakpuri E-Recycle",
    lat: 23.6219,
    lng: 77.0878,
    address: "Janakpuri, DL",
    acceptedItems: ["laptop", "hard-drive"],
    fillLevel: 90,
    status: "full",
  },
  {
    id: "dl-9",
    name: "Vasant Kunj Smart Bin",
    lat: 24.5273,
    lng: 77.75,
    address: "Vasant Kunj, DL",
    acceptedItems: ["battery", "watch"],
    fillLevel: 20,
    status: "operational",
  },
  {
    id: "dl-10",
    name: "Mayur Vihar Digital Hub",
    lat: 26.6046,
    lng: 77.2893,
    address: "Mayur Vihar, DL",
    acceptedItems: ["phone", "charger"],
    fillLevel: 45,
    status: "operational",
  },
  /* RAJASTHAN (RJ) */
{
  id: "rj-1",
  name: "Jaipur E-Waste Center",
  lat: 26.9124,
  lng: 75.7873,
  address: "MI Road, Jaipur, RJ",
  acceptedItems: ["phone", "battery", "charger"],
  fillLevel: 30,
  status: "operational",
},
{
  id: "rj-2",
  name: "Jodhpur Green Tech Bin",
  lat: 26.2389,
  lng: 73.0243,
  address: "Ratanada, Jodhpur, RJ",
  acceptedItems: ["laptop", "cable"],
  fillLevel: 55,
  status: "operational",
},
{
  id: "rj-3",
  name: "Udaipur Digital Drop",
  lat: 24.5854,
  lng: 73.7125,
  address: "Hiran Magri, Udaipur, RJ",
  acceptedItems: ["tablet", "charger"],
  fillLevel: 20,
  status: "operational",
},
{
  id: "rj-4",
  name: "Bikaner Eco Bin",
  lat: 28.0229,
  lng: 73.3119,
  address: "Civil Lines, Bikaner, RJ",
  acceptedItems: ["phone", "battery"],
  fillLevel: 65,
  status: "operational",
},
/* GUJARAT (GJ) */
{
  id: "gj-1",
  name: "Ahmedabad Smart Recycle",
  lat: 23.0225,
  lng: 72.5714,
  address: "Navrangpura, Ahmedabad, GJ",
  acceptedItems: ["phone", "laptop"],
  fillLevel: 40,
  status: "operational",
},
{
  id: "gj-2",
  name: "Surat E-Waste Hub",
  lat: 21.1702,
  lng: 72.8311,
  address: "Adajan, Surat, GJ",
  acceptedItems: ["charger", "cable"],
  fillLevel: 60,
  status: "operational",
},
{
  id: "gj-3",
  name: "Rajkot Digital Bin",
  lat: 22.3039,
  lng: 70.8022,
  address: "Kalawad Rd, Rajkot, GJ",
  acceptedItems: ["battery", "watch"],
  fillLevel: 25,
  status: "operational",
},
{
  id: "gj-4",
  name: "Bhuj Green Tech Point",
  lat: 23.2419,
  lng: 69.6669,
  address: "Madhapar, Bhuj, GJ",
  acceptedItems: ["phone", "tablet"],
  fillLevel: 50,
  status: "operational",
},
/* WEST BENGAL (WB) */
{
  id: "wb-1",
  name: "Kolkata E-Waste Hub",
  lat: 22.5726,
  lng: 88.3639,
  address: "Salt Lake, Kolkata, WB",
  acceptedItems: ["phone", "charger"],
  fillLevel: 35,
  status: "operational",
},
{
  id: "wb-2",
  name: "Howrah Smart Bin",
  lat: 22.5958,
  lng: 88.2636,
  address: "Shibpur, Howrah, WB",
  acceptedItems: ["laptop", "battery"],
  fillLevel: 60,
  status: "operational",
},
{
  id: "wb-3",
  name: "Siliguri Green Tech",
  lat: 26.7271,
  lng: 88.3953,
  address: "Sevoke Rd, Siliguri, WB",
  acceptedItems: ["tablet", "cable"],
  fillLevel: 45,
  status: "operational",
},
/* ODISHA (OD) */
{
  id: "od-1",
  name: "Bhubaneswar Digital Drop",
  lat: 20.2961,
  lng: 85.8245,
  address: "Jayadev Vihar, Bhubaneswar, OD",
  acceptedItems: ["phone", "battery"],
  fillLevel: 40,
  status: "operational",
},
{
  id: "od-2",
  name: "Cuttack E-Recycle",
  lat: 20.4625,
  lng: 85.883,
  address: "College Square, Cuttack, OD",
  acceptedItems: ["charger", "cable"],
  fillLevel: 85,
  status: "operational",
},
{
  id: "od-3",
  name: "Rourkela Smart Bin",
  lat: 22.2604,
  lng: 84.8536,
  address: "Civil Township, Rourkela, OD",
  acceptedItems: ["tablet", "watch"],
  fillLevel: 70,
  status: "operational",
},
/* ASSAM (AS) */
{
  id: "as-1",
  name: "Guwahati Eco Hub",
  lat: 26.1445,
  lng: 91.7362,
  address: "Dispur, Guwahati, AS",
  acceptedItems: ["phone", "charger"],
  fillLevel: 45,
  status: "operational",
},
{
  id: "as-2",
  name: "Silchar Digital Bin",
  lat: 24.8333,
  lng: 92.7789,
  address: "Tarapur, Silchar, AS",
  acceptedItems: ["battery", "tablet"],
  fillLevel: 20,
  status: "operational",
},
/* NORTH EAST INDIA */
{
  id: "ne-1",
  name: "Imphal Smart Recycle",
  lat: 24.817,
  lng: 93.9368,
  address: "Khwairamband, Imphal, MN",
  acceptedItems: ["phone", "cable"],
  fillLevel: 35,
  status: "operational",
},
{
  id: "ne-2",
  name: "Aizawl Green Tech",
  lat: 23.7271,
  lng: 92.7176,
  address: "Chanmari, Aizawl, MZ",
  acceptedItems: ["tablet", "charger"],
  fillLevel: 20,
  status: "operational",
},
{
  id: "ne-3",
  name: "Agartala E-Waste Point",
  lat: 23.8315,
  lng: 91.2868,
  address: "Battala, Agartala, TR",
  acceptedItems: ["battery", "watch"],
  fillLevel: 95,
  status: "operational",
},
/* BIHAR (BR) */
{
  id: "br-1",
  name: "Patna Smart E-Bin",
  lat: 25.5941,
  lng: 85.1376,
  address: "Boring Road, Patna, BR",
  acceptedItems: ["phone", "charger"],
  fillLevel: 35,
  status: "operational",
},
{
  id: "br-2",
  name: "Gaya Green Tech",
  lat: 24.7914,
  lng: 85.0002,
  address: "Civil Lines, Gaya, BR",
  acceptedItems: ["battery", "tablet"],
  fillLevel: 88,
  status: "operational",
},
{
  id: "br-3",
  name: "Muzaffarpur Digital Drop",
  lat: 26.1197,
  lng: 85.391,
  address: "Motijheel, Muzaffarpur, BR",
  acceptedItems: ["laptop", "cable"],
  fillLevel: 55,
  status: "operational",
},
/* JAMMU & KASHMIR (JK) */
{
  id: "jk-1",
  name: "Srinagar Eco Recycle",
  lat: 34.0837,
  lng: 74.7973,
  address: "Lal Chowk, Srinagar, JK",
  acceptedItems: ["phone", "battery"],
  fillLevel: 30,
  status: "operational",
},
{
  id: "jk-2",
  name: "Jammu Smart Bin",
  lat: 32.7266,
  lng: 74.857,
  address: "Gandhi Nagar, Jammu, JK",
  acceptedItems: ["charger", "cable"],
  fillLevel: 45,
  status: "operational",
},
{
  id: "jk-3",
  name: "Anantnag Green Tech",
  lat: 33.7311,
  lng: 75.1487,
  address: "KP Road, Anantnag, JK",
  acceptedItems: ["tablet", "watch"],
  fillLevel: 25,
  status: "operational",
},
/* TELANGANA (TG) */
{
  id: "tg-1",
  name: "Hyderabad E-Waste Hub",
  lat: 17.385,
  lng: 78.4867,
  address: "Banjara Hills, Hyderabad, TG",
  acceptedItems: ["phone", "laptop"],
  fillLevel: 80,
  status: "operational",
},
{
  id: "tg-2",
  name: "Gachibowli Smart Bin",
  lat: 17.4401,
  lng: 78.3489,
  address: "Gachibowli, Hyderabad, TG",
  acceptedItems: ["charger", "cable"],
  fillLevel: 55,
  status: "operational",
},
{
  id: "tg-3",
  name: "Warangal Digital Drop",
  lat: 17.9689,
  lng: 79.5941,
  address: "Hanamkonda, Warangal, TG",
  acceptedItems: ["battery", "tablet"],
  fillLevel: 20,
  status: "operational",
},
/* TAMIL NADU (TN) */
{
  id: "tn-1",
  name: "Chennai Central E-Bin",
  lat: 13.0827,
  lng: 80.2707,
  address: "T Nagar, Chennai, TN",
  acceptedItems: ["phone", "charger"],
  fillLevel: 70,
  status: "operational",
},
{
  id: "tn-2",
  name: "Coimbatore Green Tech",
  lat: 11.0168,
  lng: 76.9558,
  address: "RS Puram, Coimbatore, TN",
  acceptedItems: ["laptop", "battery"],
  fillLevel: 35,
  status: "operational",
},
{
  id: "tn-3",
  name: "Madurai Smart Recycle",
  lat: 9.9252,
  lng: 78.1198,
  address: "Anna Nagar, Madurai, TN",
  acceptedItems: ["tablet", "cable"],
  fillLevel: 20,
  status: "operational",
},
/* KERALA (KL) */
{
  id: "kl-1",
  name: "Kochi Eco Hub",
  lat: 9.9312,
  lng: 76.2673,
  address: "MG Road, Kochi, KL",
  acceptedItems: ["phone", "battery"],
  fillLevel: 45,
  status: "operational",
},
{
  id: "kl-2",
  name: "Trivandrum Digital Bin",
  lat: 8.5241,
  lng: 76.9366,
  address: "Technopark, Trivandrum, KL",
  acceptedItems: ["laptop", "charger"],
  fillLevel: 30,
  status: "operational",
},
{
  id: "kl-3",
  name: "Kozhikode Green Tech",
  lat: 11.2588,
  lng: 75.7804,
  address: "SM Street, Kozhikode, KL",
  acceptedItems: ["tablet", "cable"],
  fillLevel: 25,
  status: "operational",
},
 /* UTTAR PRADESH (UP) */
{
  id: "up-1",
  name: "Lucknow Smart E-Bin",
  lat: 26.8467,
  lng: 80.9462,
  address: "Hazratganj, Lucknow, UP",
  acceptedItems: ["phone", "charger"],
  fillLevel: 40,
  status: "operational",
},
{
  id: "up-2",
  name: "Kanpur Green Tech",
  lat: 26.4499,
  lng: 80.3319,
  address: "Kakadeo, Kanpur, UP",
  acceptedItems: ["laptop", "battery"],
  fillLevel: 55,
  status: "operational",
},
{
  id: "up-3",
  name: "Varanasi Digital Drop",
  lat: 25.3176,
  lng: 82.9739,
  address: "Lanka, Varanasi, UP",
  acceptedItems: ["tablet", "cable"],
  fillLevel: 25,
  status: "operational",
},
{
  id: "up-4",
  name: "Noida E-Waste Hub",
  lat: 28.5355,
  lng: 77.391,
  address: "Sector 62, Noida, UP",
  acceptedItems: ["phone", "laptop"],
  fillLevel: 60,
  status: "operational",
},
/* MADHYA PRADESH – JABALPUR (MP) */
{
  id: "mp-1",
  name: "Jabalpur Smart Recycle",
  lat: 23.1815,
  lng: 79.9864,
  address: "Napier Town, Jabalpur, MP",
  acceptedItems: ["phone", "battery"],
  fillLevel: 35,
  status: "operational",
},
{
  id: "mp-2",
  name: "Jabalpur Green Tech Bin",
  lat: 23.1686,
  lng: 79.9339,
  address: "Gorakhpur, Jabalpur, MP",
  acceptedItems: ["charger", "cable"],
  fillLevel: 50,
  status: "operational",
},
/* ANDHRA PRADESH (AP) */
{
  id: "ap-1",
  name: "Visakhapatnam Eco Hub",
  lat: 17.6868,
  lng: 83.2185,
  address: "Dwaraka Nagar, Vizag, AP",
  acceptedItems: ["phone", "charger"],
  fillLevel: 45,
  status: "operational",
},
{
  id: "ap-2",
  name: "Vijayawada Smart Bin",
  lat: 16.5062,
  lng: 80.648,
  address: "Benz Circle, Vijayawada, AP",
  acceptedItems: ["laptop", "battery"],
  fillLevel: 30,
  status: "operational",
},
{
  id: "ap-3",
  name: "Tirupati Digital Drop",
  lat: 13.6288,
  lng: 79.4192,
  address: "Alipiri Rd, Tirupati, AP",
  acceptedItems: ["tablet", "cable"],
  fillLevel: 20,
  status: "operational",
},
/* CHHATTISGARH (CG) */
{
  id: "cg-1",
  name: "Raipur Green Tech",
  lat: 21.2514,
  lng: 81.6296,
  address: "Shankar Nagar, Raipur, CG",
  acceptedItems: ["phone", "battery"],
  fillLevel: 40,
  status: "operational",
},
{
  id: "cg-2",
  name: "Bhilai Smart Recycle",
  lat: 21.1938,
  lng: 81.3509,
  address: "Sector 6, Bhilai, CG",
  acceptedItems: ["laptop", "charger"],
  fillLevel: 55,
  status: "operational",
},
{
  id: "cg-3",
  name: "Bilaspur Digital Bin",
  lat: 22.0797,
  lng: 82.1409,
  address: "Vyapar Vihar, Bilaspur, CG",
  acceptedItems: ["tablet", "cable"],
  fillLevel: 25,
  status: "operational",
},

];

const USERS = [
  {
    name: "Admin User",
    email: "admin@example.com",
    password: "password123",
    userType: "admin",
    points: 0,
    totalRecycled: 0,
    badges: ["System Starter"],
    co2Saved: 0,
  },
  {
    name: "Eco Warrior",
    email: "user@example.com",
    password: "password123",
    userType: "user",
    points: 150,
    totalRecycled: 5,
    badges: ["First Drop"],
    co2Saved: 12.5,
  },
];

// 4. Seeding Algorithm
const seedDB = async () => {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("Connected to MongoDB...");

    await Bin.deleteMany({});
    await User.deleteMany({});
    await Detection.deleteMany({}); // ✅ Clear detections too
    console.log("Existing bins, users, detections cleared.");

    const insertedBins = await Bin.insertMany(BINS);
    const insertedUsers = await User.insertMany(USERS);

    // ✅ Seed some recent detections for Eco Warrior
    const ecoUser = insertedUsers.find((u) => u.email === "user@example.com");

    if (ecoUser) {
      const sampleDetections = [
        {
          userId: ecoUser._id,
          type: "phone",
          name: "Smartphone",
          confidence: 92,
          weight: 0.35,
          value: 12.5,
          points: 140,
          co2Saved: 4.2,
          condition: "Good",
          confirmed: true,
        },
        {
          userId: ecoUser._id,
          type: "battery",
          name: "Battery Pack",
          confidence: 88,
          weight: 0.6,
          value: 5.4,
          points: 70,
          co2Saved: 3.0,
          condition: "Fair",
          confirmed: true,
        },
        {
          userId: ecoUser._id,
          type: "laptop",
          name: "Laptop",
          confidence: 95,
          weight: 1.7,
          value: 30.2,
          points: 350,
          co2Saved: 76.5,
          condition: "Excellent",
          confirmed: true,
        },
      ];

      await Detection.insertMany(sampleDetections);
      console.log("Sample detections seeded successfully!");
    }

    console.log(`${insertedBins.length} bins successfully seeded to the database!`);
    console.log(`${insertedUsers.length} users successfully seeded to the database!`);

    mongoose.connection.close();
    console.log("Database connection closed.");
  } catch (err) {
    console.error("Error seeding database:", err);
    mongoose.connection.close();
  }
};

seedDB();